sources:
  oracle:
    type: cdc
    logging:
      level: info
    connection:
      type: oracle
      host: dgiisrvfactqa
      port: 1521
      user: redisrdi
      password: hola1234
      database: orange
    #
    # Additional properties for the source collector:
    #
    # List of tables to be synced (optional)
    tables:
 
        efact.delegaciones:
 
          columns:
            - DELEGACION_ID

            - RNC_USUARIO

            - ES_FIRMANTE_AUTORIZADO

            - ES_SOLICITANTE_AUTORIZADO

            - ES_APROBADOR_COMERCIAL

            - ES_ADMINISTRADOR

            - FECHA_REGISTRO

            - IDENTIFICACION

            - FECHA_ACTUALIZACION
 
          keys:
 
            - DELEGACION_ID

            - DELEGACION_ID

            - RNC_DELEGADO
 
        efact.rnc_estados:
 
          columns:
 
           - RNC
 
           - ESTADO_RNC
 
           - AUTORIZADO_FACTURACION
 
           - MOTIVO_NO_FACTURACION
 
           - AUTORIZADO_SECUENCIA
 
           - MOTIVO_NO_SECUENCIA
 
           - FECHA_ULTIMA_ACTUALIZACION
 
           - CODIGO_UNIDAD
 
           - GRANDE_CONTRIBUYENTE
 
           - FECHA_REGISTRO
 
          keys:
 
           - RNC
 
        efact.facturadores_electronicos:
 
          columns:
 
           - RNC
 
           - ESTADO
 
           - FECHA_INICIO_OPERACION
 
           - FECHA_REGISTRO
 
           - FECHA_ACTUALIZACION
 
          keys:
 
           - RNC
 
 
targets:
  target:
      connection:
        type: redis
        # Host of the Redis database to which Redis Data Integration will write the processed data
        host: lnxredisndev01.dgii.local # e.g. localhost
        # Port for the Redis database to which Redis Data Integration will write the processed data
        port: 10001 # e.g. 12000
        # User of the Redis database to which Redis Data Integration will write the processed data. Uncomment if not using default user.
        # user: ${TARGET_DB_USERNAME}
        # Password for Redis target database
        password: 1234
 